### ISSUE TITLE
Unable to run, fresh git clone and import project gives errors in CarouselFeeder and BarycentricInterpoloation classes

### ISSUE THREAD

**Issue by FlyingLotus1983** [TinWhiskers/openpnp#1]
Missing libraries for `javax.vecmath.Point2d` in BarycentricInterpolation.java

Undefined method `filtered.sort` in CarouselFeeder.java

Jason probably already knows about these, but I'm creating an issue so that it doesn't get forgotten about.  It's not a super-high priority but will need to hopefully get sorted out shortly after Sept. 18.

**Comment by vonnieda** [comment]
Fixed now. Remove the dependency on vecmath and removed the calls to sort. The sort calls are JDK 8 specific so replaced them with backwards compatible versions.

**Comment by FlyingLotus1983** [comment]
I pulled the latest changes and refreshed the eclipse project.  The vecmath error is gone, but I still get errors on the sort method.  I then noticed that Eclipse was setup to use openjdk 1.7 (even though I specifically un-installed it and manually installed java jdk 1.8).  Apparently even after using the package manager to remove it, it was still there and configured by default.  I managed to make the project use java jdk 1.8 and the errors went away.

So I guess this is OK as long as openjdk is never used.

**Comment by vonnieda** [comment]
Which sort method? I thought I removed them all. Might have missed one. Make sure you clean the project, too.

**Comment by FlyingLotus1983** [comment]
Oh, sorry, this might be a problem on my end then.  I did a 'refresh', and a clean, but the errors still show up.

Eclipse complained about two, one in CarouselFeeder.java (line 125) and one in BarycentricInterpolation.java (line 79).  But if I open the files in an editor, they're newer more updated files with no sort calls.

I can't figure out how to make Eclipse show the new files.  I fucking hate Eclipse sometimes.

**Comment by vonnieda** [comment]
Cool, closing this then. For Eclipse, all you should have to do is right click on the project and select Refresh. I do this dozens of times a day and it works perfectly every time. If it's not working for you let me know and I will help.

**Comment by FlyingLotus1983** [comment]
Sorry, after I posted my last comment, I noticed that I had the line numbers wrong.  Basically, refresh / clean was working,  the sort calls are still there (but please confirm, the line #'s and files above are accurate and you should see them in there).

**Comment by vonnieda** [comment]
There are still sort calls there, but they should all be Collections.sort(...) instead of things like filtered.sort and sorted.sort. The Collections.sort should run on any VM. Can you confirm?

**Comment by FlyingLotus1983** [comment]
I'm on the TinWhiskers origin/develop branch, with main/latest pulled, and they're definitely filtered.sort / sorted.sort (not Collections.sort).  If I change the filtered.sort to Collections.sort in CarouselFeeder.java on line 125, it seems to be a valid method for openjdk 1.7, but it says that the sort in the type Collections is not applicable for the arguments new Comparator<RotatedRect>() .. I think my java-fu is weak, it can probably be made to work.

**Comment by vonnieda** [comment]
Hm. So they are. I screwed something up. Stand by.

**Comment by vonnieda** [comment]
Okay, if you pull now it should be good. I had accidentally pushed to the wrong branch. Sorry about that!

**Comment by FlyingLotus1983** [comment]
No worries, thank you for getting to this so quick.

BTW that fixed it, works fine with both of the java versions I have installed (openjdk 1.7 and java jdk 1.8).
